/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import static java.lang.System.out;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class grafprueba extends javax.swing.JFrame {

    
    /**
     * Creates new form grafprueba
     */
    public grafprueba() {
        initComponents();
        JPAgregar.setVisible(false);
        JPBuscar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        JPBuscar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JLTitout1 = new javax.swing.JLabel();
        JLAutout1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JLPclaves1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jCBSelr = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jCBSelr1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        JPAgregar = new javax.swing.JPanel();
        jTextarchivo = new javax.swing.JTextField();
        JBSeleccionar = new javax.swing.JButton();
        JBSeleccionar1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Titulo de la Investigacion");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Autores");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Palabras Claves");

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Seleccionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPBuscarLayout = new javax.swing.GroupLayout(JPBuscar);
        JPBuscar.setLayout(JPBuscarLayout);
        JPBuscarLayout.setHorizontalGroup(
            JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBuscarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBuscarLayout.createSequentialGroup()
                        .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBuscarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPBuscarLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JLPclaves1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPBuscarLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JLAutout1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPBuscarLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JLTitout1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(132, 132, 132)))
                        .addContainerGap())
                    .addGroup(JPBuscarLayout.createSequentialGroup()
                        .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBSelr1, 0, 547, Short.MAX_VALUE)
                            .addComponent(jCBSelr, 0, 547, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPBuscarLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(9, Short.MAX_VALUE))
                            .addGroup(JPBuscarLayout.createSequentialGroup()
                                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 12, Short.MAX_VALUE))))))
        );
        JPBuscarLayout.setVerticalGroup(
            JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBuscarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JLTitout1))
                .addGap(18, 18, 18)
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JLAutout1))
                .addGap(18, 18, 18)
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(JLPclaves1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jCBSelr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jCBSelr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        JPAgregar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                JPAgregarComponentHidden(evt);
            }
        });

        JBSeleccionar.setText("Seleccionar");
        JBSeleccionar.setToolTipText("");
        JBSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSeleccionarActionPerformed(evt);
            }
        });

        JBSeleccionar1.setBackground(new java.awt.Color(255, 51, 51));
        JBSeleccionar1.setForeground(new java.awt.Color(255, 255, 255));
        JBSeleccionar1.setText("Salir");
        JBSeleccionar1.setToolTipText("");
        JBSeleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSeleccionar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPAgregarLayout = new javax.swing.GroupLayout(JPAgregar);
        JPAgregar.setLayout(JPAgregarLayout);
        JPAgregarLayout.setHorizontalGroup(
            JPAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(JPAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBSeleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        JPAgregarLayout.setVerticalGroup(
            JPAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAgregarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JPAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBSeleccionar))
                .addGap(18, 18, 18)
                .addComponent(JBSeleccionar1)
                .addContainerGap(558, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(JPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(JPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jMenu3.setText("RESUMEN DE INVESTIGACIONES");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Buscar");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Agregar");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Salir");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        JPBuscar.setVisible(false);
        JPAgregar.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void JBSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSeleccionarActionPerformed
        JFileChooser fsel = new JFileChooser();
        // TITULOS BOTENES DE FILE CHOOSER
        fsel.setApproveButtonText("Ok");
        // Set the mnemonic
        fsel.setApproveButtonMnemonic('a');
        // Set the tool tip
        fsel.setApproveButtonToolTipText("New Approve Tool Tip");
        
        int result = fsel.showOpenDialog(null);

        //int result = fsel.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
 
            //fsel.showOpenDialog(null);
            File f=fsel.getSelectedFile();
            String filename=f.getAbsolutePath();
            jTextarchivo.setText(filename);
            
            System.out.print("SELECCIONO ARCHIVO->");System.out.println(filename);

            //Hashtable<String, String> tableh = new Hashtable<>(21);
            try {
                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);
                String texto="",titulo="",autores="",palabras="";
                String linea,tituloh;
                System.out.print("ENTRA EN TRY\n");
                int lineac = 0;
                while(((linea=br.readLine())) !=null){
                    System.out.print("ENTRA EN WHILE\n");
                    String[] linea_split = linea.split("\\|");
                    titulo=linea_split[0].trim();
                    autores=linea_split[1];
                    palabras=linea_split[2];
                    texto=linea_split[3];
                    tableh.put(titulo, titulo+"|"+autores+"|"+palabras+"|"+texto);
                    /*System.out.print("TITULO EN WHILE "+titulo+"\n");
                    String[] btitulo = tableh.get(titulo).split("\\|");
                    if (btitulo[0]== null) { System.out.println("NO ENCONTRO EL TITULO");
                    System.out.print("LUEGO DEL SPLIT\n");
                    }
                    System.out.println("COMPARANDO TITULOS");
                    //System.out.println(btitulo[0]);
                    System.out.println(titulo+" Largo titulo -> "+titulo.length());
                    tituloh=btitulo[0].trim();
                    System.out.println(tituloh+" Largo->"+tituloh.length());
                    System.out.println("FIN COMPARANDO TITULOS");
                                    
                
                    if (!titulo.equals(tituloh)){
                        tableh.put(titulo, titulo+"|"+palabras+"|"+autores+"|"+texto);
                        lineac ++;
                    }else{
                        JOptionPane.showMessageDialog(null, "Investigacion sobre "+titulo+" ya existe, no se agrega");
                    }
                    */
                    
                }
                if (lineac > 0){JOptionPane.showMessageDialog(null, "Se Agregaron Resumenes");}
                
                System.out.println("MUESTRA HASHTABLE");
                for (String key : tableh.keySet()){
                    System.out.println(key.hashCode() % 21 + "\t"  + key + "\t" + tableh.get(key));
                }
                System.out.println("FIN MUESTRA HASHTABLE");
                try {
                    File file = new File("hashtable.txt");
                    FileWriter fileReader = new FileWriter(file); // A stream that connects to the text file , true
                    BufferedWriter bufferedWriter = new BufferedWriter(fileReader); // Connect the FileWriter to the BufferedWriter

                    for (String key : tableh.keySet()){
                        bufferedWriter.write(tableh.get(key)+ "\n");
                    }

                    bufferedWriter.close (); // Close the stream
                } catch (Exception e) {
                    e.printStackTrace();
                }            
                }catch(Exception e){
                } // fin bloque
                
                
                JPAgregar.setVisible(false);
                jTextarchivo.setText("");
        } else if (result == JFileChooser.CANCEL_OPTION) {
            JPAgregar.setVisible(false);
            System.out.println("Cancel was selected");
        }        
    }//GEN-LAST:event_JBSeleccionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int count = 0;
        String selec = (String) jCBSelr.getSelectedItem();
        //JOptionPane.showMessageDialog(null, selec);
        String[] value_split = tableh.get(selec).split("\\|");
        JLTitout1.setText(value_split[0]);
        JLAutout1.setText(value_split[1]);
        JLPclaves1.setText(value_split[2]);
        jTextArea2.setText(value_split[3]);
        
        String palabrasclav = value_split[2];
        String[] palabrasclave;
        palabrasclave = palabrasclav.toLowerCase().split(",");
        //System.out.println(palabrasclave[0]);
        //System.out.println(palabrasclave[1]);
        //System.out.println(palabrasclave[2]);
        //System.out.println(palabrasclave[3]);
        String palabrastexto = value_split[3];
     
        String[] listWord;
        listWord = palabrastexto.replaceAll("[^a-zA-Z ]", "").toLowerCase().split("\\s+");
        int largo = listWord.length;

        // 1.Crear un Set, el Set no permite valores duplicados
        // se convierte listWord en una lista para usarlo de argumento
        // en el constructor del Set
        //Set<String> palabras = new HashSet<>(Arrays.asList(listWord));

        // 2. Se recorre el Set, no contiene palabras repetidas
        String totalPalabras = "";
        for(String word : palabrasclave){
            //System.out.println("Palabra a contar: "+word);
            word=word.trim();
            // la lógica es la misma de antes
            int iguales = 0; count = 0;
            for (int j = 0; j < largo; j++) {
                String lword = listWord[j].trim();
                iguales = lword.compareTo(word);
                if (iguales ==0) {
                    //System.out.println("iguales a buscar : "+word+"Encontro "+lword);
                    count=count+1;
                }
                
            }
            if (count > 0) {
                System.out.println(word + " " + count);
                totalPalabras += "Palabra clave: "+word+" aparece "+count+" veces.\n";
            } else {
                System.out.println(word + " " + count);
                totalPalabras += "Palabra clave: "+word+" no aparece.\n";
            }

        }
        jTextArea2.setText(value_split[3]+"\n\n"+totalPalabras);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        JPAgregar.setVisible(false);
        JPBuscar.setVisible(true);
        jCBSelr.removeAllItems();
        jCBSelr1.removeAllItems();
        // Recorro hashtable para extraer los tiulos de lista CB
        for (String key : tableh.keySet()){
            String[] value_split = tableh.get(key).split("\\|");
            jCBSelr.addItem(value_split[0]);
            
            System.out.println("autores ->"+value_split[1]);
            String[] autores = value_split[1].split(",");
            for(String autor : autores){
                System.out.println(autor+" "+value_split[0]);
                tablea.put(autor, value_split[0]);
            }
            //System.out.println(key.hashCode() % 21 + "\t"  + key + "\t" + tableh.get(key));
        }
        System.out.println("HASH MAP DE AUTORES");
        for (String key : tablea.keySet()){
            System.out.println(key+" "+tablea.get(key));
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void JPAgregarComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JPAgregarComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_JPAgregarComponentHidden

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JPBuscar.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JBSeleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSeleccionar1ActionPerformed
        JPAgregar.setVisible(false);
    }//GEN-LAST:event_JBSeleccionar1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafprueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafprueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafprueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafprueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafprueba().setVisible(true);
            }
        });
        
        //  LEER RESUMEN PREEXISTENTES //
            String f = "hashtable.txt";
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String texto="",titulo="",autores="",palabras="";
            String linea;
            int lineac = 0;
            
            while(((linea=br.readLine())) !=null){
                System.out.print("LECTURA ");System.out.println(lineac);
                System.out.println(linea);
                String[] value_split = linea.split("\\|");
                titulo=value_split[0];
                autores=value_split[1];
                palabras=value_split[2];
                texto=value_split[3];
                tableh.put(titulo, titulo+"|"+autores+"|"+palabras+"|"+texto);
                lineac ++;
            }
            System.out.println("PRECARGADOS");
                
            for (String key : tableh.keySet()){
                System.out.println(key.hashCode() % 21 + "\t"  + key + "\t" + tableh.get(key));
            }
            System.out.println("FIN MUESTRA PRECERGADOS");
        
    }

    
    
    private static Hashtable<String, String> tableh = new Hashtable<>(100);
    private static HashMap<String, String> tablea = new HashMap<>(100);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSeleccionar;
    private javax.swing.JButton JBSeleccionar1;
    private javax.swing.JLabel JLAutout1;
    private javax.swing.JLabel JLPclaves1;
    private javax.swing.JLabel JLTitout1;
    private javax.swing.JPanel JPAgregar;
    private javax.swing.JPanel JPBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCBSelr;
    private javax.swing.JComboBox<String> jCBSelr1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextarchivo;
    // End of variables declaration//GEN-END:variables
}
